services:
  database:
    image: rssantan/mysql8dev
    container_name: banco
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - bank-transaction-network

    # Serviço para rodar o Next.js
  nextjs-app:
    build:
      context: .  # Caminho para o Dockerfile
      dockerfile: Dockerfile  # Nome do Dockerfile
    container_name: nextjs_app
    env_file: .env
    ports:
      - "3000:3000"  # Porta que será exposta
    environment:
      - NODE_ENV=production
    networks:
      - bank-transaction-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - database
    env_file: .env
    restart: always
    ports:
      - 8085:80
    networks:
      - bank-transaction-network
    environment:
      - PMA_HOST=${MYSQL_SERVER}
      - PMA_PORT=3306
      - DATABASE_DRIVER=pdo_mysql
      - PMA_ARBITRARY=1

networks:
  bank-transaction-network:
    driver: bridge
