version: "3.0"
services:
  database:
    image: rssantan/mysql8dev
    container_name: banco
    env_file: ./.env
    ports:
      - "3399:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - bank-transaction-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - database
    env_file: ./.env
    restart: always
    ports:
      - 8085:80
    networks:
      - bank-transaction-network
    environment:
      - PMA_HOST=${MYSQL_SERVER}
      - PMA_PORT=3306
      - DATABASE_DRIVER=pdo_mysql
      - PMA_ARBITRARY=1

networks:
  bank-transaction-network:
    driver: bridge
